---
- hosts: localhost
  tasks:
    - name: Creating an empty file
      file:
        path: "/tech-breakfix-cantboot-002"
        state: touch
    - yum:
        name: sos
        state: present
    - yum:
        name: vim
        state: present 

    - name: 'Changing paramter in /etc/lvm/lvm.conf'
      replace:
            path: '/etc/lvm/lvm.conf'
            regexp: 'use_lvmetad = 1'
            replace: 'use_lvmetad = 0'
            backup: yes

    - name: 'Rebuild dracut'
      shell:  'dracut -fv /boot/initramfs-3.10.0-123.el7.x86_64.img 3.10.0-123.el7.x86_64'

    - lvg:
        vg: application
        pvs: /dev/vdb

    - lvol:
        vg: application
        lv: app
        size: 1G

    - filesystem:
        fstype: xfs
        dev: /dev/application/app
    - mount:
        fstype: xfs
        src: /dev/application/app
        path: /app
        state: mounted
    #- name: 'Execute break'
    #  shell: /usr/local/bin/tech-breakfix-cantboot-002 break
    #  args:
    #    executable: /bin/bash
    #- name: 'Reboot...'
    #  shell: /usr/sbin/reboot


...

